[workspace]
members = ["pebble-rust", "proc"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"
debug = true
opt-level = 2

[profile.dev]
panic = "abort"

[workspace.lints.clippy]
missing-const-for-fn = "warn"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(platform, values("aplite", "basalt", "chalk", "diorite", "emery", "flint", "gabbro"))',
] }
