[package]
name = "pebble_rust_2026"
version.workspace = true
edition.workspace = true

[lib]
test = false
doctest = false
bench = false

[dependencies]
bitflags = "2.13.1"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
critical-section = "1.2.0"
proc = { path = "../proc" }

[build-dependencies]
bindgen = "0.72.1"

[lints]
workspace = true
