[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
rustflags = [
  "-C",
  "code-model=large",
  "-C",
  "relocation-model=static",
  "-C",
  "opt-level=2",
]

[unstable]
build-std = ["core", "alloc"]
