#![no_std]

extern crate alloc;

mod action_bar_layer;
mod app;
mod app_message_result;
mod bitmap;
mod bitmap_layer;
pub mod color;
mod context;
mod custom_alloc;
mod dictionary;
mod font;
mod globals;
mod handle;
mod input;
mod key;
mod layer;
mod log;
mod persist;
mod rect;
mod simple_menu_layer;
pub mod sys;
mod text_layer;
mod time;
mod timer;
mod window;

pub use crate::action_bar_layer::{ActionBarLayer, ActionButton};
pub use crate::app::APP;
pub use crate::app::InboxSize;
pub use crate::app_message_result::AppMessageError;
pub use crate::bitmap::Bitmap;
pub use crate::bitmap_layer::BitmapLayer;
pub use crate::context::GContext;
pub use crate::custom_alloc::Allocator;
pub use crate::dictionary::{DictionaryBuilder, DictionaryView, Tuple, Value};
pub use crate::font::{Font, SystemFont};
pub use crate::input::button::Button;
pub use crate::input::click::{ClickConfig, ClickConfigBuilder, ClickRecognizer};
pub use crate::layer::Layer;
pub use crate::log::log_c_str;
pub use crate::simple_menu_layer::{SimpleMenuItem, SimpleMenuLayer, SimpleMenuSection};
pub use crate::sys::{GPoint, GRect, GSize};
pub use crate::text_layer::TextLayer;
pub use crate::time::Time;
pub use crate::timer::Timer;
pub use crate::window::Window;
pub use proc::*;
